elk_kibana:
  path: /opt/kibana
db_name: kpi_portal
db_username: liferay
db_password: liferay
liferay_home: /usr/local/liferay-portal-6.2-ce-ga6
liferay_dl_folder: "{{ liferay_home }}/data/document_library/"
liferay_default_database:
  driver: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://localhost/kpi_portal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false"
  user: "liferay"
  pass: liferay
liferay_additional_databases: []
liferay_cluster_autodetect: 127.0.0.1:3207
tomcat_home: "{{liferay_home}}/tomcat-7.0.62"

