- name: Start Elasticsearch if not started
  service: name=elasticsearch state=started

- name: wait for Elasticsearch to start
  wait_for: port=9200 delay=30

- name: copy elastic dump for kibana charts/dashboards
  synchronize: src={{playbook_dir}}/files/.kibana.tar.gz dest=/var/log/elasticsearch/.kibana.tar.gz

- name: Exexute curl command to copy kibana dump
  shell: 'curl -XPOST localhost:9200/.kibana/_import'

- name: Remove elasticdump for kibana charts/dashboards
  file: path=/var/log/elasticsearch/.kibana.tar.gz state=absent

- name: Copy KPI_CONFIG file
  template: src={{playbook_dir}}/roles/reports-conf/templates/KPI_CONFIG.properties dest=/etc/kpiconfig/KPI_CONFIG.properties

- name: Install logstash golden config filter - custom filter
  command: '/opt/logstash/bin/logstash-plugin install files/logstash-filter-goldenconfig-1.0.1.gem'

