---
- name: Create mysql dump
  mysql_db: login_user={{db_username}} login_password={{db_password}} name={{db_name}} state=dump target={{backup_restore_dir}}/kpi_portal.sql

- name: Copy 'portal-ext.properties'
  copy: src={{ liferay_home }}/portal-ext.properties dest={{ backup_restore_dir }}/portal-ext.properties

- name: Copy Liferay document data folder
  synchronize: src={{ liferay_home }}/data dest={{backup_restore_dir}} owner=yes group=yes
