---
- name: WebUpd8 apt repo
  apt_repository:
    repo='ppa:webupd8team/java'
    update_cache=yes
  when: elk_java.flavor == 'oracle' and ansible_distribution == 'Ubuntu'
  become: yes

- name: Check Oracle license
  shell:
    /usr/bin/debconf-show oracle-java8-installer |awk '/accepted-oracle-license/{print $NF}'
  become: yes
  changed_when: False
  when: elk_java.flavor == 'oracle' and ansible_distribution == 'Ubuntu'
  register: webupd8team

- name: Accept Oracle license
  shell:
    echo 'oracle-java8-installer shared/accepted-oracle-license-v1-1 select true' | /usr/bin/debconf-set-selections
  become: yes
  when: elk_java.flavor == 'oracle' and ansible_distribution == 'Ubuntu' and webupd8team.stdout != 'true'

- name: Java apt packages
  apt: pkg=oracle-java8-installer update_cache=no state=present
#  with_items: elk_java.{{ elk_java.flavor }}
  become: yes

