---
- name: Check if provided Liferay archive exists
  local_action: >
    stat path={{ liferay_archive.local }}
  register: liferay_archive_stat
  become: yes

- debug: msg=Liferay zip file exist locally  {{liferay_archive_stat.stat.exists}}

- name: Download Liferay archive if not available locally and there is url 
  local_action: >
    get_url url={{ liferay_archive.url }} dest={{ liferay_archive.local }}
  when: liferay_archive_stat.stat.exists == False and liferay_archive.url is defined
  become: yes
  run_once: true

- name: Check if provided Liferay archive exists
  local_action: >
    stat path={{ liferay_archive.local }}
  register: liferay_archive_stat
  become: yes
  failed_when: liferay_archive_stat.stat.exists == false
  
- name: Make sure unzip is installed
  become: yes
  apt: name={{ item }} state=present
  with_items:
   - unzip 

- name: Get the Liferay main folder from the archive
  local_action: > 
    shell unzip  -v {{ liferay_archive.local }} | grep -P "^[^\/]*/$" | grep -P "[^\s]*$" -o | grep -P "[^/]*" -o
  register: liferay_folder_from_zip
  become: yes
  changed_when: false
  
- name: Copy Liferay archive to remote
  become: yes
  synchronize: src={{ liferay_archive.local }} dest={{ liferay_unpack_folder }}

- name: check Liferay folder already exist
  stat: path={{ liferay_home }}
  become: yes
  register: lrfolder

- name: Copy and unpack Liferay archive 
  become: yes
  shell: 'unzip {{ liferay_unpack_folder}}/{{ liferay_archive.name}} -d {{ liferay_unpack_folder}}'
  when: lrfolder.stat.exists == False
